### ISSUE TITLE
Doesn't work on vice

### ISSUE THREAD

**Issue by haarp** [elundmark/Convert-Youtube-Embeds-to-Image-Links-UserScript#1]
Hi,

been using this for a while, pretty neat userscript. :)

It doesn't appear to work on vice.com. Example: http://motherboard.vice.com/read/chinas-biggest-secret-bitcoin-mine

Not sure what's up with that.

**Comment by elundmark** [comment]
Hi!
Not blaming the userscript I based this on, but it too has the same "flaw". I knew this was a problem, I just havn't gotten to it ( yet ). Gonna take an hour now to go through and see what I can come up with ( including issue #2 ). Shouldn't be a problem, though I'm guessing it will make it a bit heavier.

P.S.
I'm still freaked out at the url you gave as the example. No joke, I looked at the time I got the email alert from github, I looked at the _exact same video on that very page less that an hour earlier!!_ And I had the same thought, _"Huh, the script doesn't work... oh yeah I have to add x and y..."_
First I thought I had to have seen the email and subliminally looked up the video; but there's _no way_ that happened, I'd been looking at Vice videos for over an hour by then...
I mean what are odds? One in a trillion?
Freaky 8-P ...
D.S.

**Comment by haarp** [comment]
Hehe. You don't happen to be on Reddit, do you? That's where I got the link to the video :)

**Comment by elundmark** [comment]
Nope, don't have a single social account apart from Github if that counts, I'm in the 2% crowd that doesn't use it. Maybe I'm too old, or maybe it's the fact that I prefer DIY.

It's going well btw, just finished but I have to test it out on a few more sites before I upload it.

**Comment by elundmark** [comment]
Done! Check whereever you installed it from for an update, or get it [here](https://github.com/elundmark/Convert-Youtube-Embeds-to-Image-Links-UserScript/releases/tag/0.1.6).

**Comment by haarp** [comment]
Thanks! It appears to be working.

**Comment by haarp** [comment]
Oooh, cool, it also works on BoingBoing now. I didn't even think that would be possible, as they hide the video behind Javacsript. :+1:

**Comment by elundmark** [comment]
It's something I should have added to begin with really, my fav' new-ish feature: [MutationObserver](https://developer.mozilla.org/en/docs/Web/API/MutationObserver#MutationObserverInit)
