### ISSUE TITLE
Video doesn't open as child of parent tab

### ISSUE THREAD

**Issue by haarp** [elundmark/Convert-Youtube-Embeds-to-Image-Links-UserScript#2]
When one uses the Treestyle Tabs extension, opening new tabs defines the new tab as a child of the parent tab.

For some reason however, this doesn't work when left-clicking videos created by this userscript. The tab is generated as if a new tab was openend, without parent. I've never seen this happen before.

Is it possible to change the way this userscript opens links?

**Comment by elundmark** [comment]
Having read this properly I've found this to be an issue with GreaseMonkey's `GM_openInTab` which I use in the script.
Here's their [issuetracker](https://github.com/greasemonkey/greasemonkey/issues), please let them know about it :)

**Comment by haarp** [comment]
Done: https://github.com/greasemonkey/greasemonkey/issues/2087

**Comment by elundmark** [comment]
You can switch to opening the link in the same window if you prefer, by un-commenting [this] line(https://github.com/elundmark/Convert-Youtube-Embeds-to-Image-Links-UserScript/blob/master/convert_youtube_embeds_to_image_links.user.js#L35), but doing so will force you to update the script manually in the future.
